version: '3.4'

services:

  db:
    image: postgres:13
    container_name: database
    restart: always
    volumes:
      - ./Context/data/primarydb/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PrimaryDB__user}
      - POSTGRES_PASSWORD=${PrimaryDB__password}
      - POSTGRES_DB=${PrimaryDB__database}
    ports:
      - "5432:5432"
  
  order_services:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PrimaryDB__host: db
      PrimaryDB__port: 5432
      PrimaryDB__database: ${PrimaryDB__database}
      PrimaryDB__user: ${PrimaryDB__user}
      PrimaryDB__password: ${PrimaryDB__password}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db